[variables]
NPM_CONFIG_INCLUDE_WORKSPACE_ROOT = "true"
NIXPACKS_NO_MUSL = "1"

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]  
cmds = ["npm run build"]

[start]
cmd = "npm start"